/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sitiosweb.vista;

import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URISyntaxException;
import java.net.URL;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import sitiosweb.Controlador.sitiosbd;
import sitiosweb.Modelo.sitios;
import sitiosweb.modelotablas.ModelTableSitioweb;
import sitiosweb.utilidades.Utilidades;

/**
 *
 * @author USER
 */
public class VistaWeb extends javax.swing.JFrame {

    private Utilidades utilidades;
    private sitiosbd controladorSitioweb;
    private ModelTableSitioweb modelTablesitioWeb;
    private String Direccion;
    private Gestionsitiosweb gestionsitios;
    private sitios sitiosEditarEliminar;

    /**
     * Creates new form VistaWeb
     */
    public VistaWeb() {
        // Este controlador nos ayuda a poder hacer o negerar las cciones previstas en las tablas de nuestro sql
        controladorSitioweb = new sitiosbd();
        // este controlador sive para mandar la informacion a la tabla ya que la variable modelTablesitioWeb es la cual 
        //pondremos en nuestra tabala para que asi se pueda comunicar y nos a muestr los datos 
        modelTablesitioWeb = new ModelTableSitioweb(controladorSitioweb.obtenersitios(), this);
        initComponents();
        btnEnlace1.setEnabled(false);
        setLocationRelativeTo(null);
        utilidades = new Utilidades();
        gestionsitios = new Gestionsitiosweb(txtNombreWeb, txtEnlaceWeb, txtEnlaceWeb, utilidades, this);
    }

    public void limpiarsitios() {
        //Este es el metodo el cuaal nos ayudara a limpiar los campos de nuestra tabla con mayor facilidad
        txtNombreWeb.setText("");
        txtEnlaceWeb.setText("");
        jDateFechaGuardado.setDate(null);
        txtNombreWeb1.setText("");
        txtEnlaceWeb1.setText("");
        jDateFechaGuardado1.setDate(null);
    }

    public boolean isValidURL(String url) {

        try {
            new URL(Direccion).toURI();
        } catch (MalformedURLException | URISyntaxException e) {
            return false;
        }

        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jMenu1 = new javax.swing.JMenu();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNombreWeb = new javax.swing.JTextField();
        txtEnlaceWeb = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jDateFechaGuardado = new com.toedter.calendar.JDateChooser();
        btnGuardarweb = new javax.swing.JButton();
        btnEditarweb = new javax.swing.JButton();
        btnEliminarweb = new javax.swing.JButton();
        btnlimpiarcampos = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnEnlace1 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtNombreWeb1 = new javax.swing.JTextField();
        txtEnlaceWeb1 = new javax.swing.JTextField();
        jDateFechaGuardado1 = new com.toedter.calendar.JDateChooser();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        AcercaDe = new javax.swing.JMenu();

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 787, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 578, Short.MAX_VALUE)
        );

        jMenu1.setText("jMenu1");

        jMenu2.setText("File");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Edit");
        jMenuBar1.add(jMenu3);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nombre del sitio web");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Enlace del sitio web");

        jTable1.setBackground(new java.awt.Color(204, 255, 204));
        jTable1.setModel(modelTablesitioWeb);
        jTable1.setSelectionForeground(new java.awt.Color(0, 0, 255));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Fecha de guardado");

        btnGuardarweb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sitiosweb/imagenes/guardar.png"))); // NOI18N
        btnGuardarweb.setText("Guardar");
        btnGuardarweb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarwebActionPerformed(evt);
            }
        });

        btnEditarweb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sitiosweb/imagenes/buscar.png"))); // NOI18N
        btnEditarweb.setText("Editar");
        btnEditarweb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarwebActionPerformed(evt);
            }
        });

        btnEliminarweb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sitiosweb/imagenes/eliminar.png"))); // NOI18N
        btnEliminarweb.setText("Eliminar");
        btnEliminarweb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarwebActionPerformed(evt);
            }
        });

        btnlimpiarcampos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnlimpiarcampos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sitiosweb/imagenes/limpiar.png"))); // NOI18N
        btnlimpiarcampos.setText("Limpiar Campos");
        btnlimpiarcampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlimpiarcamposActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(189, Short.MAX_VALUE)
                .addComponent(btnGuardarweb)
                .addGap(18, 18, 18)
                .addComponent(btnEditarweb)
                .addGap(32, 32, 32)
                .addComponent(btnEliminarweb)
                .addGap(28, 28, 28)
                .addComponent(btnlimpiarcampos)
                .addGap(208, 208, 208))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtEnlaceWeb)
                        .addComponent(txtNombreWeb)
                        .addComponent(jDateFechaGuardado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE)))
                .addContainerGap(240, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNombreWeb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtEnlaceWeb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jDateFechaGuardado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnlimpiarcampos, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminarweb)
                    .addComponent(btnEditarweb)
                    .addComponent(btnGuardarweb))
                .addContainerGap(194, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Ingreso de datos", jPanel1);

        jPanel2.setBackground(new java.awt.Color(0, 102, 204));

        btnEnlace1.setBackground(new java.awt.Color(204, 204, 204));
        btnEnlace1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnEnlace1.setText("ABRIR ENLACE");
        btnEnlace1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnlace1ActionPerformed(evt);
            }
        });

        jTable2.setBackground(new java.awt.Color(204, 255, 204));
        jTable2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jTable2.setModel(modelTablesitioWeb);
        jTable2.setGridColor(new java.awt.Color(204, 204, 204));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable2);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nombre del sitio web");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Enlace del sitio web");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Fecha de guardado");

        txtEnlaceWeb1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtEnlaceWeb1FocusLost(evt);
            }
        });
        txtEnlaceWeb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEnlaceWeb1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEnlace1))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtNombreWeb1)
                            .addComponent(txtEnlaceWeb1)
                            .addComponent(jDateFechaGuardado1, javax.swing.GroupLayout.DEFAULT_SIZE, 583, Short.MAX_VALUE))))
                .addGap(171, 171, 171))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtNombreWeb1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtEnlaceWeb1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jDateFechaGuardado1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(btnEnlace1)
                .addContainerGap(159, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Abrir enlaces de web", jPanel2);

        jScrollPane1.setViewportView(jTabbedPane1);

        jMenu4.setText("Archivo");

        jCheckBoxMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("Salir");
        jCheckBoxMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItem1ActionPerformed(evt);
            }
        });
        jMenu4.add(jCheckBoxMenuItem1);

        jMenuBar2.add(jMenu4);

        AcercaDe.setText("Acerca de:");
        AcercaDe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AcercaDeMouseClicked(evt);
            }
        });
        jMenuBar2.add(AcercaDe);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 802, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 577, Short.MAX_VALUE)
        );

        getAccessibleContext().setAccessibleName("Gestor de web");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void actualizarTodaLasitioWeb() {
        modelTablesitioWeb.setsitios(controladorSitioweb.obtenersitios());
        modelTablesitioWeb.fireTableDataChanged();
    }
    private void btnEnlace1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnlace1ActionPerformed
        // TODO add your handling code here:
        if (java.awt.Desktop.isDesktopSupported()) {
            java.awt.Desktop desktop = java.awt.Desktop.getDesktop();
            if (desktop.isSupported(java.awt.Desktop.Action.BROWSE)) {

                try {
                    java.net.URI uri = new java.net.URI(Direccion);
                    desktop.browse(uri);
                } catch (URISyntaxException | IOException ex) {
                }
            }

        }
    }//GEN-LAST:event_btnEnlace1ActionPerformed

    private void btnlimpiarcamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlimpiarcamposActionPerformed
        // TODO add your handling code here:
        limpiarsitios();
    }//GEN-LAST:event_btnlimpiarcamposActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        // TODO add your handling code here:
        int sitios = jTable2.getSelectedRow();
        //nos sirve para q nos mande los datos al boton abrir enlace el momento de seleccionar algo de la tabla
        Direccion = (String) jTable2.getValueAt(sitios, 1);
        //nos sirve para que el boton se active en el momento de aplastar un campo de la tabla
        btnEnlace1.setEnabled(true);
    }//GEN-LAST:event_jTable2MouseClicked

    private void txtEnlaceWeb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEnlaceWeb1ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtEnlaceWeb1ActionPerformed

    private void btnGuardarwebActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarwebActionPerformed
        // TODO add your handling code here:
        ArrayList<sitios> listaSitios = new ArrayList<sitios>();
        listaSitios = controladorSitioweb.obtenersitios();
        for (sitios listaSitio : listaSitios) {
            if (listaSitio.getEnlaceweb().equals(txtEnlaceWeb.getText())) {
                JOptionPane.showMessageDialog(rootPane, "Ya existe un sitio web con este enlace en el sistema.");
                return;
            }
        }
        sitios sitio = new sitios();
        sitio.setNombreweb(txtNombreWeb.getText());
        sitio.setEnlaceweb(txtEnlaceWeb.getText());
        sitio.setFecharegistro(jDateFechaGuardado.getDate());
        if (controladorSitioweb.registrarSitios(sitio)) {
            JOptionPane.showMessageDialog(rootPane, "sitio Web guardado con éxito en el sitema.");
            limpiarsitios();
            modelTablesitioWeb.setsitios(controladorSitioweb.obtenersitios());
            modelTablesitioWeb.fireTableDataChanged();

        } else {
            JOptionPane.showMessageDialog(rootPane, "No se puede guardar el Sitio Web.", "ERROR", JOptionPane.ERROR_MESSAGE);

            if (controladorSitioweb.getEnlace(txtEnlaceWeb.getText()) != null) {
                JOptionPane.showMessageDialog(rootPane, "Ya exisye un sitio web registrado con el este enlace en el sistema.");
            } else {
            }
        }
    }//GEN-LAST:event_btnGuardarwebActionPerformed

    private void jCheckBoxMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItem1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jCheckBoxMenuItem1ActionPerformed

    private void btnEditarwebActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarwebActionPerformed
        // TODO add your handling code here:

        if (sitiosEditarEliminar == null) {
            JOptionPane.showMessageDialog(rootPane, "No hay una persona seleccionada para editar", "ERROR", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (gestionsitios.guardarEditar()) {
            sitiosEditarEliminar.setNombreweb(txtNombreWeb.getText());
            sitiosEditarEliminar.setEnlaceweb(txtEnlaceWeb.getText());
            sitiosEditarEliminar.setFecharegistro(jDateFechaGuardado.getDate());
            if (controladorSitioweb.actualizar(sitiosEditarEliminar)) {
//                JOptionPane.showMessageDialog(rootPane, "Persona editada con exito del sitema.");
                limpiarsitios();
                sitiosEditarEliminar = null;
                actualizarTodaLasitioWeb();
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Un campo es incorrecte", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnEditarwebActionPerformed

    private void btnEliminarwebActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarwebActionPerformed
        // TODO add your handling code here:
        if (sitiosEditarEliminar != null) {
            if (controladorSitioweb.eliminar(sitiosEditarEliminar)) {
                JOptionPane.showMessageDialog(rootPane, "Persona eliminada con éxito del sitema.");
                limpiarsitios();
                actualizarTodaLasitioWeb();
                limpiarsitios();
            } else {
                JOptionPane.showMessageDialog(rootPane, "No se puede eliminar la persona seleccionada.", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "No hay persona seleccionada para eliminar.", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnEliminarwebActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        //nos sirve para que el rato que seleccionamos algo en nuestra tabla nos muestre en los campos ya sea para poder editar o eliminar
        int fila = jTable1.getSelectedRow();
        String nombre = jTable1.getValueAt(fila, 0).toString();
        String enlace = jTable1.getValueAt(fila, 1).toString();
        String fecha = jTable1.getValueAt(fila, 2).toString();

        sitiosEditarEliminar = new sitios();
        sitiosEditarEliminar = controladorSitioweb.getSitio(enlace);
    }//GEN-LAST:event_jTable1MouseClicked

    private void AcercaDeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AcercaDeMouseClicked
        // TODO add your handling code here:
        AcercaDe dialog = new AcercaDe(this, true);
        dialog.setVisible(true);
    }//GEN-LAST:event_AcercaDeMouseClicked

    private void txtEnlaceWeb1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEnlaceWeb1FocusLost
        // TODO add your handling code here:
         if (btnGuardarweb.isSelected()) {
            if (txtEnlaceWeb.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "El campo enlace web no tiene datos.", "ERROR", JOptionPane.ERROR_MESSAGE);
                // Sirve para ubicar el cursor en un campo vacio.
            } else if (!utilidades.isValidURL(txtEnlaceWeb.getText())) {
                JOptionPane.showMessageDialog(this, "El enlace del sitio web ingresado no es valido", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_txtEnlaceWeb1FocusLost
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaWeb.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaWeb.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaWeb.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaWeb.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                 VistaWeb vw = new  VistaWeb();
//                 vw.setVisible(true);
                new VistaWeb().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu AcercaDe;
    private javax.swing.JButton btnEditarweb;
    private javax.swing.JButton btnEliminarweb;
    private javax.swing.JButton btnEnlace1;
    private javax.swing.JButton btnGuardarweb;
    private javax.swing.JButton btnlimpiarcampos;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private com.toedter.calendar.JDateChooser jDateFechaGuardado;
    private com.toedter.calendar.JDateChooser jDateFechaGuardado1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField txtEnlaceWeb;
    private javax.swing.JTextField txtEnlaceWeb1;
    private javax.swing.JTextField txtNombreWeb;
    private javax.swing.JTextField txtNombreWeb1;
    // End of variables declaration//GEN-END:variables

    public void clicksitios(sitios s) {
        // este metodo nos sirve par q el momento de dar un clic en la tabla se nos llenen nuestros respectivos campos
        txtNombreWeb.setText(s.getNombreweb());
        txtEnlaceWeb.setText(s.getEnlaceweb());
        jDateFechaGuardado.setDate(s.getFecharegistro());
        txtNombreWeb1.setText(s.getNombreweb());
        txtEnlaceWeb1.setText(s.getEnlaceweb());
        jDateFechaGuardado1.setDate(s.getFecharegistro());
    }

}
